language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "jruby"

before_install:
  - sudo apt-get install -y fonts-urw-base35 || true
  - sudo apt-get install -y libfreetype6-dev || true
  - sudo apt-get install -y texlive-fonts-recommended || true

script: bundle exec rspec spec
